//
//  ruleCharts.swift
//  DeltesianTranslator
//
//  Created by Liam Davidson on 2020-06-02.
//  Copyright © 2020 Liam Davidson. All rights reserved.
//

import Foundation

//Dwarven rules
var dwarvenRules = [
    " the " : " du'um ",
    " a " : " da'kal ",
    " I " : " d'tel ",
    " of " : " ag'dol ",
    " is " : " gug'd'maran ",
    " be " : " ag'dabrin ",
    " to " : " tolmar ",
    " and " : " kald ",
    " in " : " undreth ",
    " that " : " k'darg ",
    " have " : " pang'el ",
    " it " : " d'filban ",
    " for " : " gundar ",
    " not " : " ded'gil ",
    " on " : " kag'mal ",
    " with " : " gil'krad ",
    " he " : " andrug ",
    " as " : " kilkig ",
    " you " : " garn'dum ",
    " do " : " hag'drok ",
    " at " : " olg'rakin ",
    " this " : " um'drilik ",
    " but " : " dar'marath ",
    " his " : " kig ",
    " by " : " gik'let ",
    " from " : " harn'killith ",
    " they " : " juk'gom ",
    " we " : " xor ",
    " say " : " bak'harg ",
    " her " : " olo'brin ",
    " she " : " gyr'dog ",
    " or " : " kin'gar ",
    " an " : " olden'mar ",
    " will " : " gyr'ka ",
    " my " : " ballow ",
    " one " : " okra'dum ",
    " all " : " fol'had ",
    " would " : " lak'frilden ",
    " there " : " kol'banag ",
    " their " : " dim'toro ",
    " what " : " prak'la'gar ",
    " so " : " trik'dam ",
    " up " : " kamak ",
    " out " : " tik'dram ",
    " if " : " alacrog ",
    " about " : " kilarg ",
    " who " : " bak'alatar ",
    " get " : " olmahar ",
    " which " : " kijhmal ",
    " go " : " kor'lorma ",
    " me " : " adragil'ka ",
    " when " : " ul'kar ",
    " make " : " karm'iluk ",
    " can " : " oklim ",
    " like " : " narb'rank ",
    " time " : " paldrog ",
    " no " : " kognik ",
    " just " : " pik'frothar ",
    " him " : " hyrmakar ",
    " know " : " okal'dra ",
    " take " : " pin'dragok'alan ",
    " people " : " nar'grakin ",
    " into " : " nar'feloth ",
    " year " : " en'dramafor ",
    " your " : " bhan'melor ",
    " good " : " ulg'ragak ",
    " some " : " fuk'shit ",
    " could " : " shol'mag'r ",
    " them " : " hilk ",
    " see " : " ol'grahn ",
    " other " : " kig'lin ",
    " than " : " mhar'doga ",
    " then " : " un'krithik ",
    " now " : " krithil ",
    " look " : " kalsum ",
    " only " : " ilum'dra ",
    " come " : " makrok ",
    " its " : " olgan'um ",
    " over " : " krim ",
    " think " : " prolug ",
    " also " : " welnug ",
    " back " : " nugran ",
    " after " : " lik'ug ",
    " use " : " mhar'kiblik ",
    " two " : " pul'rum ",
    " how " : " thak'rum ",
    " our " : " il'dukren ",
    " work " : " pok'rim ",
    " first " : " skhi'rim ",
    " well " : " okar'gun ",
    " way " : " gyl'dreg ",
    " even " : " mak'far ",
    " new " : " park'lik ",
    " want " : " bin'gred ",
    " because " : " ghar'mortus ",
    " any " : " bal'myster ",
    " these " : " khrys ",
    " give " : " phar'dik ",
    " day " : " ban'amel ",
    " most " : " khil'dreth ",
    " us " : " yo'marik ",
    "al " : "urm ",
    "ive " : "idar ",
    "est " : "orgur ",
    "ation " : "adur ",
    "at " : "idald ",
    "ed " : "arhald ",
    "en " : "ur ",
    "eous " : "odogur ",
    "er " : "ud ",
    "es " : "ag'mar ",
    "ful " : "drak ",
    "ial " : "ourd ",
    "ble " : "gred ",
    "ic " : "yr ",
    "ing " : "uldran ",
    "ion " : "ourg ",
    "ious " : "ikrag ",
    "y " : "org ",
    "less " : "grak ",
    "ment " : "xil ",
    "ness " : "trag ",
    "e " : "urg ",
]

//generic rules
var elvenRules = [
    " the " : " lyria ",
    " a " : " il ",
    " I " : " olana ",
    " of " : " tamiira ",
    " is " : " lilti ",
    " be " : " aniir ",
    " to " : " shir'ana ",
    " and " : " oliiri ",
    " in " : " shan ",
    " that " : " spella ",
    " have " : " diminitri ",
    " it " : " wil ",
    " for " : " elniit ",
    " not " : " feen'ro ",
    " on " : " ulni ",
    " with " : " shen ",
    " he " : " torra ",
    " as " : " faenmen ",
    " you " : " healitri ",
    " do " : " maanrien ",
    " at " : " ruultis ",
    " this " : " meriann ",
    " but " : " uliri ",
    " his " : " siliara ",
    " by " : " heeril ",
    " from " : " maelfnir ",
    " they " : " faeorri ",
    " we " : " wiiren ",
    " say " : " di-milenar ",
    " her " : " astril ",
    " she " : " pliren ",
    " or " : " sol ",
    " an " : " krin ",
    " will " : " slin'lir ",
    " my " : " orastri ",
    " one " : " sigrin ",
    " all " : " soling ",
    " would " : " asol ",
    " there " : " illdi ",
    " their " : " byn ",
    " what " : " kulna ",
    " so " : " osolir ",
    " up " : " meriima ",
    " out " : " polama ",
    " if " : " hillaweer ",
    " about " : " pin-stol ",
    " who " : " ja-remlin ",
    " get " : " oliom ",
    " which " : " inada ",
    " go " : " slim'hala ",
    " me " : " ist ",
    " when " : " loliirin ",
    " make " : " maemola ",
    " can " : " quillizarin ",
    " like " : " aquarina ",
    " time " : " fliir ",
    " no " : " maninma ",
    " just " : " polarak ",
    " him " : " stellir ",
    " know " : " namiir ",
    " take " : " whelniir ",
    " people " : " asmir ",
    " into " : " lilora ",
    " year " : " uniltis ",
    " your " : " soluris ",
    " good " : " anima ",
    " some " : " spuril ",
    " could " : " lomentus ",
    " them " : " lorucia ",
    " see " : " liinimus ",
    " other " : " ilomes ",
    " than " : " othiirad ",
    " then " : " othiiron ",
    " now " : " pleraticis ",
    " look " : " ulipsiis ",
    " only " : " maana ",
    " come " : " pril ",
    " its " : " sosuma ",
    " over " : " yuriin ",
    " think " : " hal ",
    " also " : " monuurin ",
    " back " : " stalaati ",
    " after " : " brelar ",
    " use " : " iiran ",
    " two " : " slorid ",
    " how " : " sluris ",
    " our " : " othranil ",
    " work " : " stellirun ",
    " first " : " salin ",
    " well " : " somula ",
    " way " : " oshareth ",
    " even " : " monomula ",
    " new " : " quiir ",
    " want " : " stonad ",
    " because " : " okatha ",
    " any " : " driilan ",
    " these " : " stamiira ",
    " give " : " stulirik ",
    " day " : " tamaduul ",
    " most " : " striinith ",
    " us " : " buulin ",
    "al " : "amaath ",
    "ive " : "ithtik ",
    "est " : "oritus ",
    "ation " : "intil ",
    "at " : "iireth ",
    "ed " : "uumal ",
    "en " : "enthril ",
    "eous " : "idmal ",
    "er " : "erioul ",
    "es " : "edreena ",
    "ful " : "hiish ",
    "ial " : "uolin ",
    "ble " : "griin ",
    "ic " : "ythor ",
    "ing " : "umainis ",
    "ion " : "ouriin ",
    "ious " : "ildrim ",
    "y " : "errisim ",
    "less " : "sloor ",
    "ment " : "manaa ",
    "ness " : "priil ",
    "e " : "ullis ",
]

//generic rules
var Rules = [
    " the " : " b ",
    " a " : " b ",
    " I " : " b ",
    " of " : " b ",
    " is " : " b ",
    " be " : " b ",
    " to " : " b ",
    " and " : " b ",
    " in " : " b ",
    " that " : " b ",
    " have " : " b ",
    " it " : " b ",
    " for " : " b ",
    " not " : " b ",
    " on " : " b ",
    " with " : " b ",
    " he " : " b ",
    " as " : " b ",
    " you " : " b ",
    " do " : " b ",
    " at " : " b ",
    " this " : " b ",
    " but " : " b ",
    " his " : " b ",
    " by " : " b ",
    " from " : " b ",
    " they " : " b ",
    " we " : " b ",
    " say " : " b ",
    " her " : " b ",
    " she " : " b ",
    " or " : " b ",
    " an " : " b ",
    " will " : " b ",
    " my " : " b ",
    " one " : " b ",
    " all " : " b ",
    " would " : " b ",
    " there " : " b ",
    " their " : " b ",
    " what " : " b ",
    " so " : " b ",
    " up " : " b ",
    " out " : " b ",
    " if " : " b ",
    " about " : " b ",
    " who " : " b ",
    " get " : " b ",
    " which " : " b ",
    " go " : " b ",
    " me " : " b ",
    " when " : " b ",
    " make " : " b ",
    " can " : " b ",
    " like " : " b ",
    " time " : " b ",
    " no " : " b ",
    " just " : " b ",
    " him " : " b ",
    " know " : " b ",
    " take " : " b ",
    " people " : " b ",
    " into " : " b ",
    " year " : " b ",
    " your " : " b ",
    " good " : " b ",
    " some " : " b ",
    " could " : " b ",
    " them " : " b ",
    " see " : " b ",
    " other " : " b ",
    " than " : " b ",
    " then " : " b ",
    " now " : " b ",
    " look " : " b ",
    " only " : " b ",
    " come " : " b ",
    " its " : " b ",
    " over " : " b ",
    " think " : " bg ",
    " also " : " b ",
    " back " : " b ",
    " after " : " b ",
    " use " : " b ",
    " two " : " b ",
    " how " : " b ",
    " our " : " b ",
    " work " : " b ",
    " first " : " b ",
    " well " : " b ",
    " way " : " b ",
    " even " : " b ",
    " new " : " b ",
    " want " : " b ",
    " because " : " b ",
    " any " : " b ",
    " these " : " b ",
    " give " : " b ",
    " day " : " b ",
    " most " : " b ",
    " us " : " b ",
    "al " : "b ",
    "ive " : "b ",
    "est " : "b ",
    "ation " : "b ",
    "at " : "b ",
    "ed " : "b ",
    "en " : "b ",
    "eous " : "b ",
    "er " : "b ",
    "es " : "b ",
    "ful " : "b ",
    "ial " : "b ",
    "ble " : "b ",
    "ic " : "b ",
    "ing " : "b ",
    "ion " : "b ",
    "ious " : "b ",
    "y " : "b ",
    "less " : "b ",
    "ment " : "b ",
    "ness " : "b ",
    "e " : "b ",
]


